font_family         JetbrainsMono Nerd Font
font_size           10
disable_ligatures   never

cursor_trail 1

mouse_hide_wait 1.0
resize_debounce_time 0.3

url_color #0087bd
url_style curly
url_prefixes http https
detect_urls yes

enable_audio_bell no

foreground #dddddd
background #141414
selection_foreground #000000
selection_background #fffacd

background_opacity 0.75

color0  #2E2D2A
color1  #ef5e76
color2  #98c87a
color3  #f2a45c
color4  #81a8cc
color5  #d1a7c9
color6  #9ec8d0
color7  #d5d5d5
color8  #767696
color9  #dd7474
color10 #a5e0da
color11 #f5c37d
color12 #90aaf0
color13 #bebee6
color14 #cfcff0
color15 #ffffff

shell .
editor .
term xterm-kitty

wayland_titlebar_color system
linux_display_server auto

kitty_mod ctrl+shift

map ctrl+backspace      send_text all \x17
map kitty_mod+c         copy_to_clipboard
map kitty_mod+v         paste_from_clipboard
map kitty_mod+s         paste_from_selection
map kitty_mod+o         pass_selection_to_program
map kitty_mod+k         scroll_line_up
map kitty_mod+j         scroll_line_down
map kitty_mod+h         scroll_page_up
map kitty_mod+l         scroll_page_down
map kitty_mod+home      scroll_home
map kitty_mod+end       scroll_end
map kitty_mod+equal     change_font_size all +1.0
map kitty_mod+minus     change_font_size all -1.0
map kitty_mod+backspace change_font_size all 0
map kitty_mod+f5        load_config_file
map kitty_mod+f6        debug_config
