local map = vim.keymap.set
local harpoon = require("harpoon")

-- Switch numbers and symbols to avoid having to press shift in normal or visual mode
map({ 'n', 'v' }, "&", "1")
map({ 'n', 'v' }, "é", "2")
map({ 'n', 'v' }, "\"", "3")
map({ 'n', 'v' }, "'", "4")
map({ 'n', 'v' }, "(", "5")
map({ 'n', 'v' }, "-", "6")
map({ 'n', 'v' }, "è", "7")
map({ 'n', 'v' }, "_", "8")
map({ 'n', 'v' }, "ç", "9")
map({ 'n', 'v' }, "à", "0")
map({ 'n', 'v' }, "1", "&")
map({ 'n', 'v' }, "2", "é")
map({ 'n', 'v' }, "3", "\"")
map({ 'n', 'v' }, "4", "'")
map({ 'n', 'v' }, "5", "(")
map({ 'n', 'v' }, "7", "è")
map({ 'n', 'v' }, "7", "_")
map({ 'n', 'v' }, "9", "ç")
map({ 'n', 'v' }, "0", "à")
map("n", "<M-&>", function() harpoon:list():select(1) end, { desc = "Open pinned buffer 1" })
map("n", "<M-é>", function() harpoon:list():select(2) end, { desc = "Open pinned buffer 2" })
map("n", "<M-\">", function() harpoon:list():select(3) end, { desc = "Open pinned buffer 3" })
map("n", "<M-'>", function() harpoon:list():select(4) end, { desc = "Open pinned buffer 4" })
map("n", "<M-(>", function() harpoon:list():select(5) end, { desc = "Open pinned buffer 5" })
map("n", "<M-->", function() harpoon:list():select(6) end, { desc = "Open pinned buffer 6" })
map("n", "<M-è>", function() harpoon:list():select(7) end, { desc = "Open pinned buffer 7" })
map("n", "<M-_>", function() harpoon:list():select(8) end, { desc = "Open pinned buffer 8" })
